#!/usr/bin/env python3
"""
export_dongle_serials.py — 把当前已校准的 can_left_mas / can_left_slave /
can_right_mas / can_right_slave 4 个接口对应的 USB-CAN dongle iSerial 导出，
写到 config/dongle_serials.yml，并打印一份等价的 udev rules。

前置：已经跑过 `setup_can.sh`（或 calibrate_can_mapping.py），4 个符号名接口都已激活。
跑这个脚本一次，之后 activate_can_by_serial.sh 就能脱离 USB 物理口顺序激活。

用法:
  python3 piper_tools/export_dongle_serials.py             # 写 YAML + 打印 udev rules
  python3 piper_tools/export_dongle_serials.py --print-only # 只打印, 不写文件
"""

import argparse
import os
import subprocess
import sys

SYMBOLIC_IFACES = [
    "can_left_mas",
    "can_left_slave",
    "can_right_mas",
    "can_right_slave",
]

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
CONFIG_PATH = os.path.join(PROJECT_ROOT, "config", "dongle_serials.yml")


def iface_serial(iface: str) -> str:
    """sysfs walk: /sys/class/net/<iface>/device → 沿父目录找含 `serial` 文件的 USB 节点。"""
    devlink = f"/sys/class/net/{iface}/device"
    if not os.path.islink(devlink) and not os.path.exists(devlink):
        return ""
    cur = os.path.realpath(devlink)
    while cur and cur != "/":
        candidate = os.path.join(cur, "serial")
        if os.path.isfile(candidate):
            try:
                with open(candidate) as f:
                    return f.read().strip()
            except OSError:
                return ""
        cur = os.path.dirname(cur)
    return ""


def iface_is_up(iface: str) -> bool:
    try:
        out = subprocess.run(
            ["ip", "-br", "link", "show", iface],
            capture_output=True, text=True, timeout=3,
        )
        return out.returncode == 0 and "UP" in out.stdout
    except Exception:
        return False


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--print-only", action="store_true",
                    help="只打印, 不写 config/dongle_serials.yml")
    args = ap.parse_args()

    mapping = {}
    missing = []
    for iface in SYMBOLIC_IFACES:
        if not iface_is_up(iface):
            missing.append(iface)
            continue
        sn = iface_serial(iface)
        if not sn:
            missing.append(iface)
            continue
        mapping[iface] = sn

    if missing:
        print(f"[FAIL] 找不到或无法读 serial 的符号接口: {missing}", file=sys.stderr)
        print("       请先 `bash piper_tools/setup_can.sh` 让 4 个符号接口全部激活。",
              file=sys.stderr)
        sys.exit(1)

    # ── 打印结果 ────────────────────────────────────────────────────────────
    print("# dongle serial mapping (canonical iface → USB iSerial)")
    for iface, sn in mapping.items():
        print(f"  {iface:18s} → {sn}")
    print()

    # ── 写 YAML ───────────────────────────────────────────────────────────
    if not args.print_only:
        os.makedirs(os.path.dirname(CONFIG_PATH), exist_ok=True)
        with open(CONFIG_PATH, "w") as f:
            f.write("# Auto-generated by piper_tools/export_dongle_serials.py\n")
            f.write("# Maps canonical CAN iface name → USB iSerial of the gs_usb dongle\n")
            f.write("# physically wired to that arm. Used by activate_can_by_serial.sh\n")
            f.write("# to rename canX → symbolic name independent of USB port order.\n\n")
            for iface, sn in mapping.items():
                f.write(f"{iface}: '{sn}'\n")
        print(f"✓ wrote {CONFIG_PATH}")

    # ── 打印 udev rules (可选安装) ────────────────────────────────────────
    print()
    print("# Optional: install as /etc/udev/rules.d/99-piper-can.rules to get")
    print("# persistent kernel-level names (then activate_can_by_serial.sh isn't needed):")
    print("# -----------------------------------------------------------------------------")
    for iface, sn in mapping.items():
        # net rename for gs_usb-backed can ifaces. NAME= renames at netlink time.
        print(f'SUBSYSTEM=="net", ACTION=="add", DRIVERS=="gs_usb", '
              f'ATTRS{{serial}}=="{sn}", NAME="{iface}"')
    print("# -----------------------------------------------------------------------------")
    print()
    print("# Install:")
    print("#   sudo cp <above> /etc/udev/rules.d/99-piper-can.rules")
    print("#   sudo udevadm control --reload && sudo udevadm trigger")
    print()


if __name__ == "__main__":
    main()
