name: c
feature_dir: lmvla/crave/data/aloha_static_ziploc_slide_dinov3base
milestone_file: temp/newcrave_specs_base/aloha_ziploc_milestones_newmethod.npz
output_dir: lmvla/lmwm/data/recurrence_graphs/aloha_ziploc_dinov3base
smoothing_alpha: 0.001
max_product_horizon: 10
